### ISSUE TITLE
Interest in new feature?

### ISSUE THREAD

**Issue by jamessthompson** [vicberg/CombatMaster#2]
Hey, thanks for this script.  I'm using the one in roll20 (1.8?) and really like it.  I was thinking about adding a feature to allow you to add tokens to an already started encounter as a way to learn the roll20 API.  Before I get too far in I wanted to see if that was of interest or if there's another way to do it that I'm missing.

**Comment by vicberg** [comment]
I don't think its necessary.  Group-init is a better overall initiative roller.  More configurable.  I was tempted to remove the CM roll init and integrate with group init completely.  Simply highlight additional tokens to add to turnorder and issue the !group-init command and they get added.

**Comment by jamessthompson** [comment]
Oh, nice.  I didn't think about that.  Thanks!
